name: spectrum_gen
channels:
  - defaults
  - conda-forge
dependencies:
  - python == 3.13.5
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu126
    - --extra-index-url https://pypi.org/simple
    - torch==2.7.1 
    - torchvision==0.22.1
    - torchaudio==2.7.1
    - pytorch-fid==0.3.0
  - scikit-learn
  - openpyxl
  - pandas
  - matplotlib
  - imageio
  - seaborn